import { useLocation, useNavigate } from 'react-router-dom';
import type { VectorProfile } from '../types';
import { profiles, capitalOverlays, capitalBandLabels } from '../data/profiles';
import type { CapitalOverlay } from '../data/profiles';
import { allocationSuggestions, getAllocationKey } from '../data/discovery';
import ProfileHeader from '../components/result/ProfileHeader';
import RecognitionCard from '../components/result/RecognitionCard';
import ReframeCard from '../components/result/ReframeCard';
import OrientationCard from '../components/result/OrientationCard';
import CapitalBandBadge from '../components/result/CapitalBandBadge';
import EducationCards from '../components/result/EducationCards';
import BridgeCard from '../components/result/BridgeCard';

function generateDownloadContent(
  profile: VectorProfile,
  profileContent: typeof profiles[keyof typeof profiles],
  overlay: CapitalOverlay,
  allocation: { foundation: number; growth: number; conviction: number } | undefined
): string {
  const personaLabel = formatPersonaLabel(profile.persona);
  const capitalLabel = capitalBandLabels[profile.capitalBand];

  const orientationLines = profileContent.orientation
    .map((point, i) => `${i + 1}. ${point.title}: ${point.body}`)
    .join('\n');

  return `VECTOR INVESTOR PROFILE
Generated by vectorinvestor.app
---

PROFILE: ${personaLabel}
CAPITAL POSITION: ${capitalLabel}
RECOMMENDED STACKMOTIVE TIER: ${overlay.stackmotiveTier}

YOUR PROFILE
${profileContent.headline}

WHO YOU ARE
${profileContent.recognition}

THE REFRAME
${profileContent.reframe}

WHAT TO UNDERSTAND NEXT
${orientationLines}

YOUR CAPITAL POSITION
${overlay.description}

WHERE TO START IN STACKMOTIVE
${overlay.firstAction}

SUGGESTED BUCKET ALLOCATION
Foundation: ${allocation?.foundation ?? '—'}%
Growth: ${allocation?.growth ?? '—'}%
Conviction: ${allocation?.conviction ?? '—'}%

This allocation is a starting point for thinking, not a prescription.

---
Vector is part of the Sovereign Signal ecosystem.
Learn more at thesovsignal.substack.com
`;
}

function formatPersonaLabel(persona: string): string {
  return persona
    .split('-')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

export default function ResultPage() {
  const location = useLocation();
  const navigate = useNavigate();
  const vectorProfile = (location.state as { profile?: VectorProfile } | null)?.profile;

  if (!vectorProfile) {
    navigate('/', { replace: true });
    return null;
  }

  const profileContent = profiles[vectorProfile.persona];
  const overlay = capitalOverlays[vectorProfile.capitalBand];
  const bandLabel = capitalBandLabels[vectorProfile.capitalBand];

  function handleDownload() {
    if (!vectorProfile || !profileContent || !overlay) return;
    const allocationKey = getAllocationKey(vectorProfile.persona, vectorProfile.capitalBand);
    const allocation = allocationSuggestions[allocationKey];
    const content = generateDownloadContent(vectorProfile, profileContent, overlay, allocation);
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `vector-profile-${vectorProfile.persona}-${vectorProfile.capitalBand}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  return (
    <div
      style={{
        backgroundColor: 'var(--color-bg)',
        minHeight: '100vh',
      }}
    >
      <div
        className="result-container"
        style={{
          maxWidth: '680px',
          margin: '0 auto',
          padding: '48px 24px 80px',
          display: 'flex',
          flexDirection: 'column',
          gap: '32px',
        }}
      >
        {/* Section 1 — ProfileHeader */}
        <ProfileHeader
          headline={profileContent.headline}
          accentColor={profileContent.accentColor}
          capitalBandLabel={bandLabel}
          animationDelay={0}
        />

        {/* Section 2 — RecognitionCard */}
        <RecognitionCard
          recognition={profileContent.recognition}
          accentColor={profileContent.accentColor}
          animationDelay={150}
        />

        {/* Section 3 — ReframeCard */}
        <ReframeCard
          reframe={profileContent.reframe}
          accentColor={profileContent.accentColor}
          animationDelay={300}
        />

        {/* Section 4 — OrientationCard */}
        <OrientationCard
          points={profileContent.orientation}
          accentColor={profileContent.accentColor}
          animationDelay={450}
        />

        {/* Section 5 — CapitalBandBadge standalone section */}
        <div
          style={{
            animation: `fadeSlideUp 0.6s ease both`,
            animationDelay: '600ms',
          }}
        >
          <p
            style={{
              fontSize: '11px',
              textTransform: 'uppercase',
              letterSpacing: '0.1em',
              color: 'var(--color-text-muted)',
              marginBottom: '16px',
            }}
          >
            YOUR CAPITAL POSITION
          </p>
          <div style={{ marginBottom: '16px' }}>
            <CapitalBandBadge
              label={bandLabel}
              accentColor={profileContent.accentColor}
            />
          </div>
          <p
            style={{
              fontSize: '14px',
              color: 'var(--color-text-secondary)',
              lineHeight: 1.7,
              marginBottom: '12px',
            }}
          >
            {overlay.description}
          </p>
          <p
            style={{
              fontSize: '12px',
              color: 'var(--color-text-muted)',
            }}
          >
            Recommended tier: {overlay.stackmotiveTier}
          </p>
        </div>

        {/* Section 6 — EducationCards */}
        <EducationCards
          persona={vectorProfile.persona}
          accentColor={profileContent.accentColor}
          animationDelay={750}
        />

        {/* Section 7 — BridgeCard */}
        <BridgeCard
          bridgeText={profileContent.bridgeText}
          bridgeCTA={profileContent.bridgeCTA}
          firstAction={overlay.firstAction}
          accentColor={profileContent.accentColor}
          animationDelay={900}
        />

        {/* Discovery CTA */}
        <div
          style={{
            display: 'flex',
            justifyContent: 'center',
            animation: `fadeSlideUp 0.6s ease both`,
            animationDelay: '1050ms',
          }}
        >
          <button
            onClick={() => navigate('/discovery', { state: { profile: vectorProfile } })}
            style={{
              padding: '14px 28px',
              fontSize: '15px',
              fontWeight: 600,
              color: 'var(--color-text-primary)',
              backgroundColor: 'var(--color-surface)',
              border: '1px solid var(--color-border)',
              borderRadius: 'var(--radius-md)',
              cursor: 'pointer',
              transition: 'all 0.2s ease',
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.borderColor = 'var(--color-text-muted)';
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.borderColor = 'var(--color-border)';
            }}
          >
            See what this looks like as a portfolio →
          </button>
        </div>

        {/* Section 8 — Action row */}
        <div
          className="action-row"
          style={{
            display: 'flex',
            gap: '12px',
            justifyContent: 'center',
            animation: `fadeSlideUp 0.6s ease both`,
            animationDelay: '1200ms',
          }}
        >
          <button
            onClick={() => navigate('/')}
            style={{
              padding: '12px 24px',
              fontSize: '14px',
              fontWeight: 500,
              color: 'var(--color-text-secondary)',
              backgroundColor: 'transparent',
              border: '1px solid var(--color-border)',
              borderRadius: 'var(--radius-md)',
              cursor: 'pointer',
              transition: 'all 0.2s ease',
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.borderColor = 'var(--color-text-muted)';
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.borderColor = 'var(--color-border)';
            }}
          >
            Start Over
          </button>
          <button
            onClick={handleDownload}
            style={{
              padding: '12px 24px',
              fontSize: '14px',
              fontWeight: 500,
              color: 'var(--color-text-primary)',
              backgroundColor: 'var(--color-surface)',
              border: '1px solid var(--color-border)',
              borderRadius: 'var(--radius-md)',
              cursor: 'pointer',
              transition: 'all 0.2s ease',
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.borderColor = 'var(--color-text-muted)';
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.borderColor = 'var(--color-border)';
            }}
          >
            Download Profile
          </button>
        </div>
      </div>
    </div>
  );
}
